### ISSUE TITLE
请问 magento 框架中的 store 是什么？

### ISSUE THREAD

**Issue by Linnzh** [yhrhhhhh/yhr#1]
请举例。

**Comment by yhrhhhhh** [comment]
Magento 2 中的store是网站的子级。一个网站可以有多个store作为孩子。store是管理它的目录的级别。这意味着可以在不同的store拥有不同的产品和类别。客户在属于特定网站的所有商店上共享。

**Comment by Linnzh** [comment]
> Magento 2 中的store是网站的子级。一个网站可以有多个store作为孩子。store是管理它的目录的级别。这意味着可以在不同的store拥有不同的产品和类别。客户在属于特定网站的所有商店上共享。

你这里提到的 目录 是什么？请使用测试环境的信息截图标注举例。 @yhrhhhhh 
（即在测试环境中，可以在哪里 看到 Store 的信息？在哪里是“目录”？）

**Comment by yhrhhhhh** [comment]
目录截图样例：
![6](https://github.com/yhrhhhhh/yhr/assets/163226410/33755988-edb4-412c-82fa-18604e5abbc1)

![7](https://github.com/yhrhhhhh/yhr/assets/163226410/f8ff89ee-ead3-47e2-9ca0-4e700e0d655f)

名为Deutz的store信息查看：
![8](https://github.com/yhrhhhhh/yhr/assets/163226410/3d8174dd-8cb2-4b79-b083-ffb21d41da6a)

**Comment by yhrhhhhh** [comment]
商家使用magento可以开发应对于不同用户的版本，例如商家可以开发一个专门卖鞋子的版本，他的目标客户就专门是买鞋子的用户，同样也可以有女装，男装，童装，针对不同用户的版本，但同时这些版本都可以用同一后台进行管理，而这些女装，鞋子，男装这些专卖版本就是所谓的store。

**Comment by Linnzh** [comment]
> 商家使用magento可以开发应对于不同用户的版本，例如商家可以开发一个专门卖鞋子的版本，他的目标客户就专门是买鞋子的用户，同样也可以有女装，男装，童装，针对不同用户的版本，但同时这些版本都可以用同一后台进行管理，而这些女装，鞋子，男装这些专卖版本就是所谓的store。

也可以这么理解吧……Store 就是 店铺。店铺可以卖不同的产品，也可以是相同的产品只是 目标客户在不一样的地区，等等，它只是“店铺”。

![image](https://github.com/yhrhhhhh/yhr/assets/37938141/b5231a8d-bdc4-4e70-902d-05b69bc7af92)
