### ISSUE TITLE
数据库查询操作

### ISSUE THREAD

**Issue by Linnzh** [yhrhhhhh/yhr#10]
请完成以下任务，并分次提交代码，以及综述编码过程中遇到的问题和解决方案。

以下代码均写在模块 `Example_Started`中。

- [x] Controller 接口：使用原生 SQL 查询，获取表 `catalog_category_entity` 中的前 20 条数据，最终返回一个 JSON 对象
- [x] Controller 接口：使用集合类`\Magento\Catalog\Model\ResourceModel\Category\Collection`查询 category（分类）的前 20 条数据，最终返回一个 JSON 对象
- [x] Block 页面：使用原生 SQL 查询，获取表 `catalog_category_entity` 中的前 20 条数据，最终返回一个 **使用无序列表展示结果**的 HTML 页面
- [x] Block 页面：使用集合类`\Magento\Catalog\Model\ResourceModel\Category\Collection`查询 category（分类）的前 20 条数据，最终返回一个 **使用无序列表展示结果**的 HTML 页面

最后展示运行截图。

**Comment by yhrhhhhh** [comment]
编码过程中遇到的问题：
**问题1**
`ReflectionException: Class "Magento\Framework\App\Http\Interceptor" does not exist`

解决方案：

Set permission to folders:
```sudo chmod -R 777 var/ pub/ generated/```
then run below commands:
```
php bin/magento setup:upgrade

php bin/magento setup:di:compile

php bin/magento setup:static-content:deploy -f

chmod -R 777 var/ generated/
```
**问题2**
报错：
```
 main.DEBUG: Request validation failed for action "Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor" {"exception":"[object] (Magento\\Framework\\App\\Request\\InvalidRequestException(code: 0): Invalid request received at /workspace/F2/app/code/Magento/Backend/App/Request/BackendValidator.php:176)"} []
[2024-03-20 05:20:14] main.WARNING: Failed to retrieve the release notification content. The response is: Response body is empty. [] []
```

解决方案：Controller容器问题，使用 Magento 2 控制器实现了Magento\Framework\App\Action\HttpGetActionInterface 接口

**问题3**
报错：

```
Error: Typed property Example\Started\Controller\Query\Collection::$categoryCollectionFactory must not be accessed before initialization in /workspace/F2/app/code/Example/Started/Controller/Query/Collection.php:25
Stack trace:
```
解决方案：

解决这个问题，需要确保在访问 $categoryCollectionFactory 属性之前先进行初始化。在构造函数中，需要将传入的 
$categoryCollectionFactory 参数赋值给对应的属性。

**问题4**

报错：
```
1 exception(s):
Exception #0 (Exception): Notice: Undefined variable: block2 in /workspace/F2/app/code/Example/Started/view/frontend/templates/category_list.phtml on line 8
```
解决方案：

确保在模板文件中使用了正确的变量名。由于使用了 $block 变量来传递数据，因此需要修改模板文件中的变量名为 $block。

### 运行截图
**Controller 接口：使用原生 SQL 查询，获取表 catalog_category_entity 中的前 20 条数据，最终返回一个 JSON 对象**
![Raw1](https://github.com/yhrhhhhh/yhr/assets/163226410/d1a920ff-c4fc-41f4-8c26-401baac5d88f)

**Controller 接口：使用集合类\Magento\Catalog\Model\ResourceModel\Category\Collection查询 category（分类）的前 20 条数据，最终返回一个 JSON 对象**
![Collection2](https://github.com/yhrhhhhh/yhr/assets/163226410/f72f8a15-fb85-47b2-94dc-fb288b73ed49)

**Block 页面：使用原生 SQL 查询，获取表 catalog_category_entity 中的前 20 条数据，最终返回一个 使用无序列表展示结果的 HTML 页面**

![block1](https://github.com/yhrhhhhh/yhr/assets/163226410/5a30fd23-a2bf-484b-aee5-e100796cb30a)


 **Block 页面：使用集合类\Magento\Catalog\Model\ResourceModel\Category\Collection查询 category（分类）的前 20 条数据，最终返回一个 使用无序列表展示结果的 HTML 页面**

![block2](https://github.com/yhrhhhhh/yhr/assets/163226410/a78d2d08-7e41-433c-a8be-42931ce0191f)
