### ISSUE TITLE
在测试环境进行下单，并使用 Bank 支付。

### ISSUE THREAD

**Issue by Linnzh** [yhrhhhhh/yhr#4]
请提供以下信息：

- 下单的商品：链接、SKU、下单数量
- 下单的账号
- 下单成功的截图

如果有遇到任何问题或者报错，请提供截图说明。

**Comment by yhrhhhhh** [comment]
下单商品链接：https://www.jeeda.net/24v-25a-battery-charger-0400087-400087-for-jlg-universal-replacement
商品名称：24V 25A Battery Charger 0400087 400087 for JLG Universal Replacement
该商品SKU：HP34169-25
下单数量：2
下单账号：1517924726@qq.com
订单号：JD240314169759
下单页面截图：
![4](https://github.com/yhrhhhhh/yhr/assets/163226410/b9f138cd-73df-464f-b975-b773e04234bf)
下单成功截图：
![5](https://github.com/yhrhhhhh/yhr/assets/163226410/2b6b0f79-58da-4185-a871-0aa0c95bb9ad)
操作过程问题：无
