### ISSUE TITLE
启动 magento 项目，并使用 markdown 语法描述其安装过程，最后附上运行成功的截图

### ISSUE THREAD

**Issue by Linnzh** [yhrhhhhh/yhr#6]
包括运行代码，以及运行命令各参数的含义。

**Comment by yhrhhhhh** [comment]
安装过程描述：
# Magento 项目安装过程

## 下载 Magento

使用 Composer 下载 Magento 项目：
composer install

## 创建数据库

在数据库服务器上创建一个新的数据库，用于存储 Magento 的数据。同时，创建一个数据库用户并授予该用户对该数据库的访问权限。

## 安装 Magento
进入 Magento 项目根目录，并执行以下命令安装 Magento：
php bin/magento setup:install \
--base-url=http://start.kyoye.com --backend-frontname=admin --db-host=localhost \
--db-name=get_started_magento --db-user=dev --db-password=magento@2023 \
--admin-firstname=Alice --admin-lastname=Ada --admin-email=dev@alice.com \
--admin-user=alice --admin-password=alice@2024 --language=en_US \
--currency=USD --timezone=America/Chicago --use-secure=0 --use-secure-admin=0 \
--use-rewrites=1 --search-engine=elasticsearch7 --elasticsearch-host=127.0.0.1 \
--elasticsearch-port=9200 --elasticsearch-enable-auth=1 --elasticsearch-username=elastic \
--elasticsearch-password=linnzh --elasticsearch-index-prefix=get-started-magento --elasticsearch-timeout=15 \
--session-save=redis --amqp-host=127.0.0.1 --amqp-port=5672 \
--amqp-user=guest --amqp-password=guest --amqp-virtualhost=/ \
--amqp-ssl=0 --consumers-wait-for-messages=0 --lock-provider=file \
--lock-file-path=var/lock --cleanup-database

( --db-name、--db-user、--db-password：MySQL 数据库名称、用户名和密码。
--cache-backend=redis、--cache-backend-redis-server、--cache-backend-redis-db：配置 Redis 缓存。
--page-cache=redis、--page-cache-redis-server、--page-cache-redis-db：配置 Redis 页面缓存。
--elasticsearch-host、--elasticsearch-port、--elasticsearch-username、--elasticsearch-password：配置 OpenSearch（ElasticSearch）连接信息。)
安装完成后，您可以访问 Magento 网站并登录后台管理页面。

##启动 Magento
打开浏览器，访问 Magento 网站地址，例如 http://localhost/。然后在地址后面加上 /admin 进入后台管理页面，输入管理员账号和密码进行登录。

运行成功的截图：
![10](https://github.com/yhrhhhhh/yhr/assets/163226410/9858c92a-4a87-4e87-82f0-252bc4566e8d)

**Comment by yhrhhhhh** [comment]
--base-url: 指定 Magento 网站的基本 URL，这里设置为 http://start.kyoye.com。
--backend-frontname: Magento 后台管理页面的访问路径，这里设置为 admin。
--db-host: 数据库的主机地址，这里设置为 localhost。
--db-name: 数据库名称，这里设置为 get_started_magento。
--db-user 和 --db-password: 数据库的用户名和密码，这里设置为 dev 和 magento@2023。
--admin-firstname 和 --admin-lastname: 管理员的名字和姓氏，这里设置为 Alice 和 Ada。
--admin-email: 管理员的邮箱地址，这里设置为 dev@alice.com。
--admin-user 和 --admin-password: 管理员的用户名和密码，这里设置为 alice 和 alice@2024。
--language: Magento 的默认语言，这里设置为 en_US。
--currency: Magento 的默认货币，这里设置为 USD。
--timezone: Magento 的时区，这里设置为 America/Chicago。
--use-secure 和 --use-secure-admin: 是否使用 HTTPS 连接，这里都设置为 0 表示不使用。
--use-rewrites: 是否启用 URL 重写，这里设置为 1 表示启用。
--search-engine: 搜索引擎的类型，这里设置为 elasticsearch7 表示使用 Elasticsearch 7。
--elasticsearch-host 和 --elasticsearch-port: Elasticsearch 的主机地址和端口号，这里设置为 127.0.0.1 和 9200。
--elasticsearch-enable-auth: 是否启用 Elasticsearch 的认证，这里设置为 1 表示启用。
--elasticsearch-username 和 --elasticsearch-password: Elasticsearch 的用户名和密码，这里设置为 elastic 和 linnzh。
--elasticsearch-index-prefix: Elasticsearch 的索引前缀，这里设置为 get-started-magento。
--elasticsearch-timeout: Elasticsearch 的超时时间，这里设置为 15 秒。
--session-save: 会话存储类型，这里设置为 redis 表示使用 Redis。
--amqp-host, --amqp-port, --amqp-user, --amqp-password, --amqp-virtualhost, --amqp-ssl: 设置 AMQP（高级消息队列协议）连接的参数。
--consumers-wait-for-messages: 是否等待消息队列中的消息，这里设置为 0 表示不等待。
--lock-provider: 使用的锁提供者，这里设置为 file 表示使用文件锁。
--lock-file-path: 锁文件的路径，这里设置为 var/lock。
--cleanup-database: 在安装前是否清理数据库，这里设置为 true 表示清理。
