### ISSUE TITLE
在后台创建 3 个分类及 3 个产品

### ISSUE THREAD

**Issue by Linnzh** [yhrhhhhh/yhr#8]
提供在后台创建成功的截图，以及在前端视图展示的截图。

**Comment by yhrhhhhh** [comment]
### 后台创建成功的截图
**产品创建成功截图**
![000](https://github.com/yhrhhhhh/yhr/assets/163226410/a93a4fba-f937-466a-a68b-a12db5039769)
**目录创建成功截图：**
![Category](https://github.com/yhrhhhhh/yhr/assets/163226410/39cd7fe1-98c4-42aa-9927-8666234873d9)
