### ISSUE TITLE
在测试网站的不同 store 下单，不需要注册账号（即匿名用户）

### ISSUE THREAD

**Issue by Linnzh** [yhrhhhhh/yhr#9]
在 US 和 France 2 个网站下单即可。提供下单成功的截图。

**Comment by yhrhhhhh** [comment]
**在UD网站下单成功截图：**
![expend](https://github.com/yhrhhhhh/yhr/assets/163226410/27e44d71-c171-4ba3-8ffb-e6da6762480a)
**在France**
![expend2](https://github.com/yhrhhhhh/yhr/assets/163226410/6e71a1d8-b269-4d5c-810c-f8c989eb2ef3)
